sinknode:
  build:
    context: ./
    dockerfile: Dockerfile-rpi
  command: ["4", "mosquitto1:1883", "mosquitto2:1883"]
  links:
    - mosquitto1
    - mosquitto2
  restart: always

drain:
  build:
    context: ./
    dockerfile: Dockerfile-rpi
  entrypoint: ['./drain.rb']
  command: ["mosquitto2"]
  volumes:
    - ./data:/src/data
  links:
    - mosquitto2
  restart: always

publisherhigh:
  image: rranshous/mosquitto-rpi
  links:
    - mosquitto1
  command: bash -c 'sleep 5 && mosquitto_pub -h mosquitto1 -p 1883 -t level/7 -m "test"'
  restart: always

publisherlow:
  image: rranshous/mosquitto-rpi
  links:
    - mosquitto1
  command: bash -c 'sleep 10 && mosquitto_pub -h mosquitto1 -p 1883 -t level/2 -m "test"'
  restart: always

#logger-1:
#  image: rranshous/mosquitto-rpi
#  links:
#    - mosquitto1
#  command: mosquitto_sub -v -h mosquitto1 -p 1883 -t '#' -q 2
#  restart: always

#logger-2:
#  image: rranshous/mosquitto-rpi
#  links:
#    - mosquitto2
#  command: mosquitto_sub -v -h mosquitto2 -p 1883 -t '#' -q 2
#  restart: always

mosquitto1:
  image: rranshous/mosquitto-rpi
  ports:
    - "9001:9001"
    - "1883:1883"

mosquitto2:
  image: rranshous/mosquitto-rpi
  ports:
    - "9002:9001"
    - "1884:1883"

